server:
  port: 28081
  servlet:
    encoding:
      #      charset: UTF-8
      #      enabled: true
      force: true

spring.devtools:
  livereload:
    enabled: true

spring.datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password:
  minimum-idle: 10
  maximum-pool-size: 50
  idle-timeout: 10000
  connection-timeout: 10000
  validation-timeout: 10000
  max-lifetime: 580000
  #  connection-test-query: SELECT 1
  pool-name: HOSUK

#spring.jpa:
#  hibernate:
#    ddl-auto: create

#  spring.datasource.initialization-mode=always 세팅)
#  spring boot 2.5 이상 버전의 경우 자동으로 실행되지 않아 spring.sql.init.mode=always

spring.mustache:
  suffix: .html