DROP table if exists Article;
create table Article(
  ID bigint generated by default as identity,
  TITLE varchar(255),
  BODY varchar(255),
  AUTHOR varchar(255),
  PUBLISH_DATE varchar(255),
  PRIMARY KEY ( ID )
);