logging:
  level:
    #root: DEBUG
    hs.springboot.example.openfeign.themoviedb.integration.*: DEBUG

server:
  port: 9999

spring:
  application:
    name: your-application-name

# FeignClient ??
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000